CREATE TABLE USERS(
   Id_USER SERIAL,
   login VARCHAR(24)  NOT NULL,
   nickname VARCHAR(24),
   password VARCHAR(100) ,
   avatar_path VARCHAR(256) ,
   status SMALLINT NOT NULL,
   token_2fa VARCHAR(100) ,
   has_2fa BOOLEAN NOT NULL,
   PRIMARY KEY(Id_USER)
);

CREATE TABLE CHANNELS(
   Id_CHANNEL SERIAL,
   type SMALLINT NOT NULL,
   password VARCHAR(61) ,
   name VARCHAR(30)  NOT NULL,
   Id_USER INTEGER NOT NULL,
   PRIMARY KEY(Id_CHANNEL),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER)
);

CREATE TABLE MESSAGES(
   Id_CHANNEL INTEGER,
   Id_USER INTEGER,
   Id_Message SERIAL,
   date_msg TIMESTAMP NOT NULL,
   content VARCHAR(512)  NOT NULL,
   PRIMARY KEY(Id_CHANNEL, Id_USER, Id_Message),
   FOREIGN KEY(Id_CHANNEL) REFERENCES CHANNELS(Id_CHANNEL),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER)
);

CREATE TABLE BANNED(
   Id_CHANNEL INTEGER,
   Id_USER INTEGER,
   Id_BANNED SERIAL,
   PRIMARY KEY(Id_CHANNEL, Id_USER, Id_BANNED),
   FOREIGN KEY(Id_CHANNEL) REFERENCES CHANNELS(Id_CHANNEL),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER)
);

CREATE TABLE CHANNEL_INVITE(
   Id_CHANNEL INTEGER,
   Id_USER INTEGER,
   Id_INVITATION SERIAL,
   PRIMARY KEY(Id_CHANNEL, Id_USER, Id_INVITATION),
   FOREIGN KEY(Id_CHANNEL) REFERENCES CHANNELS(Id_CHANNEL),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER)
);

CREATE TABLE MUTE(
   Id_CHANNEL INTEGER,
   Id_USER INTEGER,
   Id_MUTE SERIAL,
   PRIMARY KEY(Id_CHANNEL, Id_USER, Id_MUTE),
   FOREIGN KEY(Id_CHANNEL) REFERENCES CHANNELS(Id_CHANNEL),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER)
);

CREATE TABLE GAME(
   Id_GAME SERIAL,
   P1_score INTEGER,
   P2_score INTEGER,
   game_type SMALLINT NOT NULL,
   start_date TIMESTAMP,
   PRIMARY KEY(Id_GAME)
);

CREATE TABLE MATCHMAKING(
   Id_MATCHMAKING SERIAL,
   Id_USER INTEGER,
   PRIMARY KEY(Id_MATCHMAKING),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER)
);

CREATE TABLE CHALLENGE(
   Id_USER INTEGER,
   Id_USERS_1 INTEGER,
   Id_CHALLENGE SERIAL,
   accepted BOOLEAN NOT NULL,
   PRIMARY KEY(Id_USER, Id_USERS_1, Id_CHALLENGE),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER),
   FOREIGN KEY(Id_USERS_1) REFERENCES USERS(Id_USER)
);

CREATE TABLE FOLLOW(
   Id_USER INTEGER,
   Id_USERS_1 INTEGER,
   PRIMARY KEY(Id_USER, Id_USERS_1),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER),
   FOREIGN KEY(Id_USERS_1) REFERENCES USERS(Id_USER)
);

CREATE TABLE SUBSCRIBE(
   Id_USER INTEGER,
   Id_USERS_1 INTEGER,
   PRIMARY KEY(Id_USER, Id_USERS_1),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER),
   FOREIGN KEY(Id_USERS_1) REFERENCES USERS(Id_USER)
);

CREATE TABLE BLOCK(
   Id_USER INTEGER,
   Id_USERS_1 INTEGER,
   PRIMARY KEY(Id_USER, Id_USERS_1),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER),
   FOREIGN KEY(Id_USERS_1) REFERENCES USERS(Id_USER)
);

CREATE TABLE JOINED(
   Id_USER INTEGER,
   Id_CHANNEL INTEGER,
   PRIMARY KEY(Id_USER, Id_CHANNEL),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER),
   FOREIGN KEY(Id_CHANNEL) REFERENCES CHANNELS(Id_CHANNEL)
);

CREATE TABLE ADMINISTRATE(
   Id_USER INTEGER,
   Id_CHANNEL INTEGER,
   PRIMARY KEY(Id_USER, Id_CHANNEL),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER),
   FOREIGN KEY(Id_CHANNEL) REFERENCES CHANNELS(Id_CHANNEL)
);

CREATE TABLE PLAY(
   Id_USER INTEGER,
   Id_GAME INTEGER,
   PRIMARY KEY(Id_USER, Id_GAME),
   FOREIGN KEY(Id_USER) REFERENCES USERS(Id_USER),
   FOREIGN KEY(Id_GAME) REFERENCES GAME(Id_GAME)
);